name: 'jsPerformoBot'
description: 'Check for performance suggestions.'

inputs:
  repo-token:
    description: 'github security token'
    required: true

runs:
  using: 'node12'
  main: 'firstAction.js'
