name: 'jePerformoBot'
author: 'Florian Markusse'
description: 'Uses jsPerformoBot to check for performance improvements.'
inputs:
  repo-token:
    description: 'github security token'
    required: true

runs:
  using: 'node12'
  main: 'action.mjs'